POST http://localhost:3000/users/
Content-Type: application/json

{
  "name": "Juan",
  "username": "juan024",
  "email": "juan024@gmail.com"
}

###
DELETE http://localhost:3000/users/6841f59cacdb5e84b9bfb9ff
